[OutputChannels]

ochGetCommand = "O%2o%2c"

; see TS_OUTPUT_SIZE in console source code

ochBlockSize = @@TS_TOTAL_OUTPUT_SIZE@@

; 11.2.3 Full Optimized – High Speed

; scatteredOchGetCommand = @@TS_GET_SCATTERED_GET_COMMAND_char@@

; scatteredOffsetArray = highSpeedOffsets

;#if CONN_SLOW

; scatteredGetEnabled = { 1 }

;#else

; scatteredGetEnabled = { 0 }

;#endif

;

; see TunerStudioOutputChannels struct

;

@@BOARD_OUTPUT_CHANNELS_FROM_FILE@@

@@OUTPUTS_SECTION_FROM_FILE@@